FROM {{ config.get("os.name") }}:{{ config.get("os.version") }} as prod-base

WORKDIR "{{ config.get("os.workDirectory") }}"
CMD ["/usr/bin/supervisord","-c","/etc/supervisor/supervisord.conf"]
ENV LC_ALL={{ config.get("os.locale") }}

{% if config.get("nodejs.enabled") and config.get("nodejs.target")=="base" %}
    {%- include "Dockerfile/partials/nvm.Dockerfile.twig" -%}
{% endif %}
ADD docker/docker-setup-base.sh /docker-setup-base.sh
RUN /docker-setup-base.sh

FROM prod-base as tooling
{% if config.get("nodejs.enabled") and config.get("nodejs.target")=="tooling" %}
    {%- include "Dockerfile/partials/nvm.Dockerfile.twig" %}
{% endif %}
ADD docker/docker-setup-tooling.sh /docker-setup-tooling.sh
RUN /docker-setup-tooling.sh

FROM tooling as builder

FROM prod-base as prod-final
