FROM {{ config.get("os.name") }}:{{ config.get("os.version") }} as prod-base

WORKDIR "{{ config.get("os.workDirectory") }}"
CMD ["/usr/bin/supervisord","-c","/etc/supervisor/supervisord.conf"]
ENV LC_ALL={{ config.get("os.locale") }}

{% set supervisorFiles=["docker/supervisord/00_supervisord.conf"] %}
{%- if config.get("webserver.enabled") -%}
    {%- if config.get("webserver.software")=="apache" -%}
        {%- set supervisorFiles=supervisorFiles|merge(["docker/supervisord/01_apache.conf"]) -%}
    {%- endif -%}
    {%- if config.get("php.enabled") and config.get("php.webserverIntegrationType")=="php_fpm" -%}
        {%- set supervisorFiles=supervisorFiles|merge(["docker/supervisord/01_php_fpm.conf"]) -%}
    {%- endif -%}
{%- endif -%}
COPY ["{{ supervisorFiles|join('", "')|raw }}", "/etc/supervisor/conf.d/"]

{% if config.get("nodejs.enabled") and config.get("nodejs.target")=="base" %}
    {%- include "Dockerfile/partials/nvm.Dockerfile.twig" -%}
{% endif %}
ADD docker/docker-setup-base.sh /docker-setup-base.sh
RUN /docker-setup-base.sh

FROM prod-base as tooling
{% set supervisorFilesTooling=[] %}
{% if config.get("nodejs.enabled") and config.get("nodejs.target")=="tooling" %}
    {%- include "Dockerfile/partials/nvm.Dockerfile.twig" %}
{% endif %}
{%- if config.get("project.type")=="symfony" and "symfony/webpack-encore-bundle" in config.get("symfony.modules") -%}
    {%- set supervisorFilesTooling=supervisorFilesTooling|merge(["docker/supervisord/02_nodejs_symfony.conf"]) -%}
{%- endif -%}
{%- if config.get("project.type")=="symfony" -%}
    {%- set supervisorFilesTooling=supervisorFilesTooling|merge(["docker/supervisord/03_symfony_logcat.conf"]) -%}
{%- endif -%}
{% if supervisorFilesTooling|length > 0 %}
COPY ["{{ supervisorFilesTooling|join('", "')|raw }}", "/etc/supervisor/conf.d/"]
{% endif %}

ADD docker/docker-setup-tooling.sh /docker-setup-tooling.sh
RUN /docker-setup-tooling.sh

FROM tooling as builder

FROM prod-base as prod-final
