parameters:
  app.cli_tools:
    joe:
      name: 'joe (text editor)'
      package:
        'ubuntu-all': 'joe'
    rsync:
      name: 'rsync'
      package:
        'ubuntu-all': 'rsync'
    nano:
      name: 'nano (text editor)'
      package:
        'ubuntu-all': 'nano'
    git:
      name: 'git'
      package:
        'ubuntu-all': 'git'
    unzip:
      name: 'unzip'
      package:
        'ubuntu-all': 'unzip'
    cron:
      name: 'cron'
      package:
        'ubuntu-all': 'cron'
    rsyslog:
      name: 'rsyslog'
      package:
        'ubuntu-all': 'rsyslog'
    logrotate:
      name: 'logrotate'
      package:
        'ubuntu-all': 'logrotate'
