parameters:
  app.phpExtensions:
    amqp:
      name: amqp
      package:
        'ubuntu-20.04-7.4': 'php7.4-amqp'
    apcu:
      name: APCu
      package:
        'ubuntu-20.04-7.4': 'php7.4-apcu'
    bcmath:
      name: bcmath
      package:
        'ubuntu-20.04-7.4': 'php7.4-bcmath'
    bzip2:
      name: bzip2
      package:
        'ubuntu-20.04-7.4': 'php7.4-bz2'
    ctype:
      name: ctype
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    exif:
      name: EXIF
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    fileinfo:
      name: Fileinfo
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    ffi:
      name: FFI
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    ftp:
      name: FTP
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    calendar:
      name: Calendar
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    curl:
      name: cURL
      package:
        'ubuntu-20.04-7.4': 'php7.4-curl'
    gmagick:
      name: GraphicsMagick
      package:
        'ubuntu-20.04-7.4': 'php7.4-gmagick'
    gnupg:
      name: GnuPG
      package:
        'ubuntu-20.04-7.4': 'php7.4-gnupg'
    imagick:
      name: ImageMagick
      package:
        'ubuntu-20.04-7.4': 'php7.4-imagick'
    memcache:
      name: memcache
      package:
        'ubuntu-20.04-7.4': 'php7.4-memcache'
    memcached:
      name: 'memcached (using libmemcached)'
      package:
        'ubuntu-20.04-7.4': 'php7.4-memcached'
    mongodb:
      name: MongoDB
      package:
        'ubuntu-20.04-7.4': 'php7.4-mongodb'
    ssh2:
      name: SSH
      package:
        'ubuntu-20.04-7.4': 'php7.4-ssh2'
    uploadprogress:
      name: 'upload progress'
      package:
        'ubuntu-20.04-7.4': 'php7.4-uploadprogress'
    uuid:
      name: UUID
      package:
        'ubuntu-20.04-7.4': 'php7.4-uuid'
    xdebug:
      name: XDebug
      package:
        'ubuntu-20.04-7.4': 'php7.4-xdebug'
    grpc:
      name: gRPC
      package:
        'ubuntu-20.04-7.4': 'php7.4-grpc'
    imap:
      name: IMAP
      package:
        'ubuntu-20.04-7.4': 'php7.4-imap'
    inotify:
      name: inotify
      package:
        'ubuntu-20.04-7.4': 'php7.4-inotify'
    intl:
      name: Internationalization
      package:
        'ubuntu-20.04-7.4': 'php7.4-intl'
    ldap:
      name: ldap
      package:
        'ubuntu-20.04-7.4': 'php7.4-ldap'
    mbstring:
      name: mbstring
      package:
        'ubuntu-20.04-7.4': 'php7.4-mbstring'
    mcrypt:
      name: libmcrypt
      package:
        'ubuntu-20.04-7.4': 'php7.4-mcrypt'
    mysql:
      name: MySQL
      package:
        'ubuntu-20.04-7.4': 'php7.4-mysql'
    odbc:
      name: ODBC
      package:
        'ubuntu-20.04-7.4': 'php7.4-odbc'
    protobuf:
      name: protobuf
      package:
        'ubuntu-20.04-7.4': 'php7.4-protobuf'
    radius:
      name: RADIUS
      package:
        'ubuntu-20.04-7.4': 'php7.4-radius'
    redis:
      name: Redis
      package:
        'ubuntu-20.04-7.4': 'php7.4-redis'
    snmp:
      name: SNMP
      package:
        'ubuntu-20.04-7.4': 'php7.4-snmp'
    soap:
      name: XML-SOAP
      package:
        'ubuntu-20.04-7.4': 'php7.4-soap'
    xml:
      name: XML
      package:
        'ubuntu-20.04-7.4': 'php7.4-xml'
    gd:
      name: 'GD graphics library'
      package:
        'ubuntu-20.04-7.4': 'php7.4-gd'
    gettext:
      name: 'GNU gettext'
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    gmp:
      name: 'gmp'
      package:
        'ubuntu-20.04-7.4': 'php7.4-gmp'
    json:
      name: JSON
      package:
        'ubuntu-20.04-7.4': 'php7.4-json'
    pgsql:
      name: pgSQL
      package:
        'ubuntu-20.04-7.4': 'php7.4-pgsql'
    readline:
      name: Readline
      package:
        'ubuntu-20.04-7.4': 'php7.4-readline'
    sqlite3:
      name: SQLite 3
      package:
        'ubuntu-20.04-7.4': 'php7.4-sqlite3'
    zip:
      name: ZIP
      package:
        'ubuntu-20.04-7.4': 'php7.4-zip'
    lz4:
      name: LZ4
      package:
        'ubuntu-20.04-7.4': 'php7.4-lz4'
    solr:
      name: Solr
      package:
        'ubuntu-20.04-7.4': 'php7.4-solr'
    iconv:
      name: iconv
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    pdo:
      name: PDO
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    phar:
      name: PHAR
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    posix:
      name: POSIX
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    shmop:
      name: shmop
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    sockets:
      name: Sockets
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    sysvmsg:
      name: sysvmsg
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    sysvsem:
      name: sysvsem
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    sysvshm:
      name: sysvshm
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
    tokenizer:
      name: Tokenizer
      package:
        'ubuntu-20.04-7.4': 'php7.4-common'
