parameters:
  app.templateMappings:
    "Dockerfile/Dockerfile.twig":
      target: "docker/Dockerfile"
    "docker-setup/base.sh.twig":
      target: "docker/docker-setup-base.sh"
      chmod: 0o775
    "docker-setup/tooling.sh.twig":
      target: "docker/docker-setup-tooling.sh"
      chmod: 0o775
    "supervisord/00_supervisord.conf.twig":
      target: "docker/supervisord/00_supervisord.conf"
    "supervisord/01_apache.conf.twig":
      target: "docker/supervisord/01_apache.conf"
    "supervisord/01_php_fpm.conf.twig":
      target: "docker/supervisord/01_php_fpm.conf"
      if: "#php.webserverIntegrationType# === 'php_fpm'"
    "supervisord/02_nodejs_symfony.conf.twig":
      target: "docker/supervisord/02_nodejs_symfony.conf"
      if: "#project.type# === 'symfony' && in_array('symfony/webpack-encore-bundle', #symfony.modules#)"
    "supervisord/03_apache_logcat.conf.twig":
      target: "docker/supervisord/03_apache_logcat.conf"
      if: "#webserver.enabled# === true && #webserver.software# === 'apache'"
    "supervisord/03_symfony_logcat.conf.twig":
      target: "docker/supervisord/03_symfony_logcat.conf"
      if: "#project.type# === 'symfony'"
    "docker-compose/docker-compose.yml.twig":
      target: "docker/docker-compose.yml"
