parameters:
  app.templateMappings:
    "Dockerfile/Dockerfile.twig":
      target: "docker/Dockerfile"
    "docker-setup/base.sh.twig":
      target: "docker/docker-setup-base.sh"
      chmod: 0o775
    "docker-setup/tooling.sh.twig":
      target: "docker/docker-setup-tooling.sh"
      chmod: 0o775
    "supervisord/00_supervisord.conf.twig":
      target: "docker/supervisord/00_supervisord.conf"
    "supervisord/01_apache.conf.twig":
      target: "docker/supervisord/01_apache.conf"
    "supervisord/01_php_fpm.conf.twig":
      target: "docker/supervisord/01_php_fpm.conf"
      if: "#php.webserverIntegrationType# === 'php_fpm'"
    "docker-compose/docker-compose.yml.twig":
      target: "docker/docker-compose.yml"
