parameters:
  app.tree.initial:
    welcome:
      type: banner
      description: |-
        Please configure the base details of your project (type, software stack).
        Except the type, everything can be changed later on.

    project.name:
      type: string
      description: 'the name of the project'
      defaultDescription: 'name of current directory'
      mandatory: true
      default: 'basename(getcwd())'
      defaultEval: true

    project.type:
      type: select_single
      description: 'the project type'
      options:
        symfony: 'Symfony web/console app'
        drupal: 'Drupal site'
        wordpress: 'Wordpress site'
        reactjs: 'ReactJS app'
        gatsby: 'Gatsby app'
        generic_nodejs_web: 'Other NodeJS static-compiled web app (nuxt, jekyll, ...)'
        generic_nodejs_server: 'NodeJS server app or web app with dynamic NodeJS backend (react dom-server, ...)'
        generic_static_web: 'Generic static Web content'
        generic_php_web: 'Generic PHP Web content'
        generic_php_cli: 'Generic PHP CLI application'
      optionsConfiguration:
        symfony:
          set:
            php.enabled: true
            externalServices.enabled: true
            os.workDirectory: '/var/www'
            os.documentRoot: 'public'
            'os.cliTools.tooling.[]':
              - unzip #composer
              - git #composer
        drupal:
          set:
            php.enabled: true
            webserver.enabled: true
            externalServices.enabled: true
            os.workDirectory: '/var/www'
            os.documentRoot: 'web'
            'os.cliTools.tooling.[]':
              - unzip
              - git
            'os.cliTools.base.[]':
              - cron #drush cron
              - logrotate
        wordpress:
          set:
            php.enabled: true
            webserver.enabled: true
            externalServices.enabled: true
            os.workDirectory: '/var/www'
            'os.cliTools.tooling.[]':
              - unzip
              - git
            'os.cliTools.base.[]':
              - cron #wp cron
              - logrotate
        generic_php_web:
          set:
            php.enabled: true
            webserver.enabled: true
            externalServices.enabled: true
            os.workDirectory: '/var/www'
            'os.cliTools.tooling.[]':
              - unzip
              - git
            'os.cliTools.base.[]':
              - cron
              - logrotate
        generic_php_cli:
          set:
            php.enabled: true
            externalServices.enabled: true
            os.workDirectory: '/opt/app'
            'os.cliTools.tooling.[]':
              - unzip
              - git
        reactjs:
          set:
            nodejs.enabled: true
            webserver.enabled: true
            nodejs.target: tooling
            os.workDirectory: '/opt/app'
            os.documentRoot: 'public'
        gatsby:
          set:
            nodejs.enabled: true
            webserver.enabled: true
            nodejs.target: tooling
            os.workDirectory: '/opt/app'
            os.documentRoot: 'public'
        generic_nodejs_web:
          set:
            nodejs.enabled: true
            webserver.enabled: true
            nodejs.target: tooling
            os.workDirectory: '/opt/app'
            os.documentRoot: 'public'
        generic_nodejs_server:
          set:
            nodejs.enabled: true
            externalServices.enabled: true
            nodejs.target: base
            os.workDirectory: '/opt/app'
        generic_static_web:
          set:
            webserver.enabled: true
            os.workDirectory: '/var/www'
            os.documentRoot: ''
            'os.cliTools.base.[]':
              - cron
              - logrotate
      final: true
      mandatory: true

    os.name:
      type: select_single
      description: 'the base OS for the Docker images'
      options:
        ubuntu: Ubuntu
        debian: Debian
        alpine: Alpine
      default: ubuntu
      mandatory: true

    os.ubuntu_version:
      # Support matrix at https://wiki.ubuntu.com/Releases
      type: select_single
      if: '#os.name# === ''ubuntu'''
      pathOverride: 'os.version'
      description: 'the Ubuntu version for the Docker images'
      options:
        '18.04': '18.04 LTS'
        '20.04': '20.04 LTS'
        '22.04': '22.04 LTS'
      default: '22.04'
      mandatory: true

    os.debian_version:
      # Support matrix at https://www.debian.org/releases/
      type: select_single
      if: '#os.name# === ''debian'''
      pathOverride: 'os.version'
      description: 'the Debian version for the Docker images'
      options:
        buster: 'buster / oldoldstable'
        bullseye: 'bullseye / oldstable'
        bookworm: 'bookworm / stable'
        trixie: 'trixie / testing'
      default: buster
      mandatory: true

    os.alpine_version:
      # Support matrix at https://alpinelinux.org/releases/
      type: select_single
      if: '#os.name# === ''alpine'''
      pathOverride: 'os.version'
      description: 'the Alpine version for the Docker images'
      options:
        '3.13': '3.13 (2021-01)'
        '3.14': '3.14 (2021-06)'
        '3.15': '3.15 (2021-11)'
        '3.16': '3.16 (2022-05)'
        '3.17': '3.17 (2022-11)'
        '3.18': '3.18 (2023-05)'
        '3.19': '3.19 (2023-11)'
      default: '3.19'
      mandatory: true

    os.locale:
      type: select_single
      description: 'the default locale for the Docker images'
      default: 'C.UTF-8'
      mandatory: true
      options:
        #TODO need a way to avoid typing down 364 locale definitions from /usr/share/i18n/locales
        #keep those I need (C, en-US, de-DE) and do this later
        'C': 'C (ANSI, English)'
        'C.UTF-8': 'C (UTF-8, English)'
        'en_US.UTF-8': 'en_US (UTF-8)'
        'de_DE.UTF-8': 'de_DE (UTF-8)'

    os.timezone:
      type: select_single
      description: 'the default timezone for the Docker images'
      default: 'Etc/UTC'
      mandatory: true
      options:
        #TODO need a way to avoid typing down 629 TZ definitions from /usr/share/zoneinfo/posix/
        'Etc/UTC': 'UTC'
        'Europe/Berlin': 'Europe/Berlin'

    php.version:
      # Support matrix at
      # https://www.php.net/supported-versions.php (language)
      # https://deb.sury.org/#php-packages (Ubuntu/Debian)
      # Note 8.1 is unsupported in Ubuntu (https://github.com/oerdnj/deb.sury.org/issues/1439)
      # https://github.com/codecasts/php-alpine (Alpine)
      type: select_single
      description: 'the PHP version'
      if: '#php.enabled# === true && in_array(#os.name#,[''ubuntu''])'
      options:
        '7.4': 'PHP 7.4'
        '8.0': 'PHP 8.0'
        '8.1': 'PHP 8.1'
        '8.2': 'PHP 8.2'
        '8.3': 'PHP 8.3'
      default: '8.3'
      mandatory: true

    webserver.software:
      type: select_single
      description: 'the web server'
      if: '#webserver.enabled# === true'
      mandatory: true
      options:
        apache: Apache
        nginx: Nginx
        lighttpd: lighttpd
      default: apache

    php.webserverIntegrationType:
      type: select_single
      description: 'the PHP integration'
      if: '#webserver.enabled# === true && #php.enabled# === true'
      options:
        mod_php: mod_php
        php_fpm: PHP-FPM
      mandatory: true
      optionsConfiguration:
        mod_php:
          if: '#webserver.software# === ''apache'''
          default_if: '#webserver.software# === ''apache'''
        php_fpm:
          default_if: '#webserver.software# !== ''apache'''

    symfony.type:
      type: select_single
      description: 'Symfony project type'
      if: '#project.type# == ''symfony'''
      mandatory: true
      options:
        web: 'Web (enables web server)'
        cli: 'CLI/other (no web server)'
      optionsConfiguration:
        web:
          set:
            webserver.enabled: true
            'os.cliTools.base.[]':
              - cron #php sessions
              - logrotate #logs
            'php.extensions.base.[]':
              # see https://symfony.com/doc/current/setup.html
              - ctype
              - iconv
              - xml
              - tokenizer
              - curl
              - intl
            'php.extensions.tooling.[]':
              - xdebug
        cli:
          set:
            webserver.enabled: null
            'php.extensions.base.[]':
              # see https://symfony.com/doc/current/setup.html
              - ctype
              - iconv
              - xml
              - tokenizer
              - curl
              - intl
            'php.extensions.tooling.[]':
              - xdebug

    symfony.modules:
      type: select_multi
      description: 'Symfony bundles and packs'
      if: '#project.type# == ''symfony'''
      options:
        symfony/console: Console
        symfony/ldap: LDAP
        symfony/form: Forms
        symfony/twig-pack: Twig
        symfony/maker-bundle: 'Maker bundle'
        doctrine/doctrine-bundle: 'Doctrine Base'
        orm-fixtures: 'Doctrine Fixtures'
        doctrine/doctrine-migrations-bundle: 'Doctrine Migrations'
        symfony/monolog-bundle: 'Monolog Logger'
        symfony/apache-pack: 'Apache integration'
        symfony/cache: Cache
        symfony/profiler-pack: 'Profiler pack'
        symfony/mailer: Mailer
        symfony/phpunit-bridge: 'PHPUnit bridge'
        symfony/security-bundle: Security
        symfony/serializer: Serializer
        symfony/translation: Translation
        symfony/webpack-encore-bundle: 'Webpack / Encore bundle'
      optionsConfiguration:
        symfony/apache-pack:
          if: '#webserver.software# === ''apache'''
          default_if: '#webserver.software# === ''apache'''
        symfony/webpack-encore-bundle:
          set:
            nodejs.enabled: true
            nodejs.packageManager: npm
            nodejs.version: lts/iron
            nodejs.target: tooling
        symfony/mailer:
          set:
            'externalServices.types.[]': mail

    php.extensions.base:
      type: select_multi
      description: 'the PHP extensions to install in the base image'
      if: '#php.enabled# === true'
      options: 'app.phpExtensions'

    php.extensions.tooling:
      type: select_multi
      description: 'additional PHP extensions to install in the tooling image'
      if: '#php.enabled# === true'
      options: 'app.phpExtensions'

    php.composer.enabled:
      type: boolean
      description: 'if Composer should be used'
      if: '#php.enabled# === true'
      default: true

    php.composer.jsonPath:
      type: string
      description: 'the relative path of the directory containing composer.json'
      defaultDescription: 'empty (composer.json in root path)'
      if: '#php.composer.enabled# === true'
      default: ''

    php.composer.vendorDir:
      type: string
      description: 'the relative path of Composer''s vendor directory'
      if: '#php.composer.enabled# === true'
      mandatory: true
      default: 'vendor'

    php.composer.binDir:
      type: string
      description: 'the relative path of Composer''s bin directory'
      if: '#php.composer.enabled# === true'
      mandatory: true
      default: 'bin'

    externalServices.types:
      type: select_multi
      description: 'additional services'
      if: '#externalServices.enabled# === true'
      options:
        mariadb: MariaDB
        mysql: MySQL
        postgres: PostgreSQL
        mongodb: MongoDB
        sqlite: SQLite
        mail: 'Mailcatcher (dummy SMTP server)'
        redis: 'Redis Cache'
        elasticsearch: ElasticSearch
        memcached: Memcached
        ldap: 'OpenLDAP + phpldapadmin'
        solr: Solr
      optionsConfiguration:
        mariadb:
          set:
            'php.extensions.base.[]': mysql
        mysql:
          set:
            'php.extensions.base.[]': mysql
        postgres:
          set:
            'php.extensions.base.[]': pgsql
        mongodb:
          set:
            'php.extensions.base.[]': mongodb
        sqlite:
          set:
            'php.extensions.base.[]': sqlite3
        redis:
          set:
            'php.extensions.base.[]': redis
        memcached:
          set:
            'php.extensions.base.[]': memcache
        ldap:
          set:
            'php.extensions.base.[]': ldap
        solr:
          set:
            'php.extensions.base.[]': solr

    externalServices.mariadb.version:
      # Support matrix at https://mariadb.com/kb/en/mariadb-server-release-dates/
      type: select_single
      description: 'the MariaDB version'
      if: '#externalServices.enabled# === true && in_array(''mariadb'', #externalServices.types#)'
      options:
        '10.3': 'MariaDB 10.3'
        '10.4': 'MariaDB 10.4'
        '10.5': 'MariaDB 10.5'
        '10.6': 'MariaDB 10.6'
        '10.7': 'MariaDB 10.7'
        '10.8': 'MariaDB 10.8'
        '10.9': 'MariaDB 10.9'
        '10.10': 'MariaDB 10.10'
        '10.11': 'MariaDB 10.11'
        '11.0': 'MariaDB 11.0'
        '11.1': 'MariaDB 11.1'
        '11.2': 'MariaDB 11.2'
        '11.3': 'MariaDB 11.3'
# Not released yet
#        '11.4': 'MariaDB 11.4'
#        '11.5': 'MariaDB 11.5'
      default: '11.3'
      mandatory: true

    nodejs.version:
      type: select_single
      description: 'the NodeJS version'
      if: '#nodejs.enabled# === true'
      options:
        'lts/dubnium': 'v10 LTS (dubnium)'
        'lts/erbium': 'v12 LTS (erbium)'
        'lts/fermium': 'v14 LTS (fermium)'
        'lts/gallium': 'v16 LTS (gallium)'
        'lts/hydrogen': 'v18 LTS (hydrogen)'
        'lts/iron': 'v20 LTS (iron)'
      default: 'lts/hydrogen'
      mandatory: true

    nodejs.packageManager:
      type: select_single
      description: 'the NodeJS package manager'
      if: '#nodejs.enabled# === true'
      options:
        npm: 'npm'
        yarn: 'yarn'
      default: yarn
      mandatory: true

    os.workDirectory:
      type: string
      mandatory: true
      description: 'the Docker image''s working directory (WORKDIR directive)'
      if: '#os.workDirectory# === null'
    os.documentRoot:
      type: string
      mandatory: true
      description: 'the Docker image''s web server document root, relative to the work directory'
      if: '#os.documentRoot# === null && #webserver.enabled# === true'

    os.cliTools.base:
      type: select_multi
      description: 'additional CLI tools in base image'
      options: 'app.cli_tools'
    os.cliTools.tooling:
      type: select_multi
      description: 'additional CLI tools in tooling image'
      options: 'app.cli_tools'
